import {
  SAFE_SPEAK_COMMUNITY_PROFILES,
  SAFE_SPEAK_CULTURAL_PROFILES,
  SAFE_SPEAK_FAITH_PROFILES,
  SAFE_SPEAK_PRIORITY_LANGUAGE_OPTIONS
} from '@modules/scope/scope.constants';

export const DEFAULT_PROFILE_LANGUAGE = 'en';
export const DEFAULT_PROFILE_JURISDICTION = 'NSW';

export const LANGUAGE_OPTIONS = SAFE_SPEAK_PRIORITY_LANGUAGE_OPTIONS.map(({ code, label }) => ({
  code,
  label
}));

export const CULTURAL_PROFILE_OPTIONS = SAFE_SPEAK_CULTURAL_PROFILES;

export const FAITH_PROFILE_OPTIONS = SAFE_SPEAK_FAITH_PROFILES;

export const COMMUNITY_PROFILE_OPTIONS = SAFE_SPEAK_COMMUNITY_PROFILES;
